# Generated by Django 4.2.7 on 2023-11-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("ingredients", models.TextField(blank=True)),
                ("recipe_text", models.TextField(blank=True)),
                (
                    "cooking_time",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "quantity_of_servings",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
