# Generated by Django 4.2.7 on 2023-11-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["-time_create"], name="recipes_app_time_cr_bb374e_idx"
            ),
        ),
    ]
