# Generated by Django 4.2.7 on 2023-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_app", "0003_alter_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликовано")], default=1
            ),
        ),
    ]
